In [1]:
#numpy
#used to work with arrays and matrix

In [2]:
import numpy as np

In [3]:
#create a one dimensional array
list1 = [1,2,3,4,5]

In [4]:
oneDimExample = np.array(list1)

In [5]:
print(list1)

[1, 2, 3, 4, 5]


In [6]:
oneDimExample

array([1, 2, 3, 4, 5])

In [7]:
#number of dimensiosn in array
oneDimExample.ndim

1

In [8]:
#number of elements in array
oneDimExample.shape

(5,)

In [9]:
#type of array
type(oneDimExample)

numpy.ndarray

In [10]:
#create 2D array
twoDimExample = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [11]:
twoDimExample

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
twoDimExample.shape

(3, 3)

In [14]:
twoDimExample.ndim

2

In [15]:
type(twoDimExample)


numpy.ndarray

In [16]:
#numpy matrix

matrix = np.matrix(([[1,2,3],[4,5,6],[7,8,9]]))

In [17]:
matrix * matrix

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])