In [1]:
import numpy as np

In [2]:
list1 = [10, 11,27]

In [3]:
print(type(list1))

<class 'list'>


In [7]:
#convert list to array
array1 = np.array(list1)

In [8]:
print(type(array1))

<class 'numpy.ndarray'>


In [9]:
print(array1)

[10 11 27]


In [ ]:
#we can create n dimension arrays

In [10]:
print(array1.ndim)

1


In [11]:
print(array1.shape)

(3,)


In [14]:
print(array1.dtype)

int64


In [13]:
#create 1D array from a list
#here we have a nested list
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
print(arr.ndim)

2


In [ ]:
#coneverting list into arrays as shown above 
#arrrays used for performing numberical opertaions
#arrays have less computational time than list 

In [18]:
height = [63,64,75,23,78,57,89,67]

In [19]:
h = np.array(height)
h = h*0.0245
h

array([1.5435, 1.568 , 1.8375, 0.5635, 1.911 , 1.3965, 2.1805, 1.6415])

In [20]:
l = [1,2,3,4]
print(l*2)

[1, 2, 3, 4, 1, 2, 3, 4]


In [21]:
l_m = [w*2 for w in l]
l_m

[2, 4, 6, 8]

In [ ]:
# a list can be accessed using index
#to get last element in list you can use -1

In [ ]:
#some math functions can be used on list 

In [22]:
arr1 = np.arange(10)

In [23]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
print(np.sin(arr1))
#this function not available in list

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]


In [25]:
#you can reshape your arrays
print(arr1.shape)


(10,)


In [26]:
print(arr1.reshape(2,5))
#row,column

[[0 1 2 3 4]
 [5 6 7 8 9]]
